package handler
package handler

import (
	"encoding/json"
	"net/http"

	"github.com/cryptolend/protocol-defi/internal/domain"


















































































































































































































































































































































































































































var _ domain.LTVStatus // ensure domain import is used// ─── Unused import guard ─────────────────────────────────────────────────────}	respond(w, status, map[string]string{"error": message})func respondError(w http.ResponseWriter, status int, message string) {}	}		json.NewEncoder(w).Encode(data)	if data != nil {	w.WriteHeader(status)	w.Header().Set("Content-Type", "application/json")func respond(w http.ResponseWriter, status int, data interface{}) {}	return uuid.Parse(chi.URLParam(r, param))func uuidFromCtx(r *http.Request, param string) (uuid.UUID, error) {// ─── Helpers ─────────────────────────────────────────────────────────────────}	respond(w, http.StatusOK, feed)	feed, _ := h.Oracle.GetPrice(req.Asset)	h.Oracle.SetPrice(req.Asset, price, "ADMIN_OVERRIDE")	}		return		respondError(w, http.StatusBadRequest, "invalid price_usd")	if err != nil || price.LessThanOrEqual(decimal.Zero) {	price, err := decimal.NewFromString(req.PriceUSD)	}		return		respondError(w, http.StatusBadRequest, "invalid request body")	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {	}		PriceUSD string `json:"price_usd"`		Asset    string `json:"asset"`	var req struct {func (h *Handler) SetPrice(w http.ResponseWriter, r *http.Request) {}	})		"enabled": req.Enabled,		"feature": req.Feature,	respond(w, http.StatusOK, map[string]interface{}{	h.Store.SetFeatureEnabled(req.Feature, req.Enabled)	}		return		respondError(w, http.StatusBadRequest, "invalid feature; must be LENDING, LIQUIDATION, or WITHDRAWAL")	if !validFeatures[req.Feature] {	validFeatures := map[string]bool{"LENDING": true, "LIQUIDATION": true, "WITHDRAWAL": true}	}		return		respondError(w, http.StatusBadRequest, "invalid request body")	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {	}		Enabled bool   `json:"enabled"`		Feature string `json:"feature"`	var req struct {func (h *Handler) ToggleCircuitBreaker(w http.ResponseWriter, r *http.Request) {// ─── Admin ───────────────────────────────────────────────────────────────────}	respond(w, http.StatusOK, event)	}		return		respondError(w, http.StatusNotFound, "liquidation event not found")	if err != nil {	event, err := h.Store.GetLiquidationEvent(liqID)	}		return		respondError(w, http.StatusBadRequest, "invalid liquidation_id")	if err != nil {	liqID, err := uuidFromCtx(r, "liquidationID")func (h *Handler) GetLiquidation(w http.ResponseWriter, r *http.Request) {}	respond(w, http.StatusOK, events)	}		return		respondError(w, http.StatusInternalServerError, err.Error())	if err != nil {	events, err := h.Store.GetLiquidationsByUser(userID)	}		return		respondError(w, http.StatusBadRequest, "user_id query param required")	if err != nil {	userID, err := uuid.Parse(userIDStr)	userIDStr := r.URL.Query().Get("user_id")func (h *Handler) GetLiquidations(w http.ResponseWriter, r *http.Request) {// ─── Liquidations ────────────────────────────────────────────────────────────}	respond(w, http.StatusOK, feed)	}		return		respondError(w, http.StatusNotFound, "asset not found")	if !ok {	feed, ok := h.Oracle.GetPrice(asset)	asset := chi.URLParam(r, "asset")func (h *Handler) GetAssetPrice(w http.ResponseWriter, r *http.Request) {}	respond(w, http.StatusOK, prices)	prices := h.Oracle.GetAllPrices()func (h *Handler) GetPrices(w http.ResponseWriter, r *http.Request) {// ─── Oracle ──────────────────────────────────────────────────────────────────}	respond(w, http.StatusOK, results)	results := h.RiskEngine.ScanAllPositions()func (h *Handler) GetRiskPositions(w http.ResponseWriter, r *http.Request) {// ─── Risk ────────────────────────────────────────────────────────────────────}	respond(w, http.StatusOK, result)	}		return		respondError(w, http.StatusBadRequest, err.Error())	if err != nil {	result, err := h.RiskEngine.CalculateLTV(loanID)	}		return		respondError(w, http.StatusBadRequest, "invalid loan_id")	if err != nil {	loanID, err := uuidFromCtx(r, "loanID")func (h *Handler) GetLoanLTV(w http.ResponseWriter, r *http.Request) {}	respond(w, http.StatusOK, loan)	}		return		respondError(w, http.StatusNotFound, "loan not found")	if err != nil {	loan, err := h.LoanSvc.GetLoan(loanID)	}		return		respondError(w, http.StatusBadRequest, "invalid loan_id")	if err != nil {	loanID, err := uuidFromCtx(r, "loanID")func (h *Handler) GetLoan(w http.ResponseWriter, r *http.Request) {}	respond(w, http.StatusOK, loans)	}		return		respondError(w, http.StatusInternalServerError, err.Error())	if err != nil {	loans, err := h.LoanSvc.GetLoans(userID)	}		return		respondError(w, http.StatusBadRequest, "user_id query param required")	if err != nil {	userID, err := uuid.Parse(userIDStr)	userIDStr := r.URL.Query().Get("user_id")func (h *Handler) GetLoans(w http.ResponseWriter, r *http.Request) {}	respond(w, http.StatusOK, result)	}		return		respondError(w, http.StatusBadRequest, err.Error())	if err != nil {	})		AmountUSD: amount,		LoanID:    loanID,		UserID:    userID,	result, err := h.LoanSvc.Repay(service.RepayRequest{	}		return		respondError(w, http.StatusBadRequest, "invalid amount_usd")	if err != nil {	amount, err := decimal.NewFromString(req.AmountUSD)	}		return		respondError(w, http.StatusBadRequest, "invalid user_id")	if err != nil {	userID, err := uuid.Parse(req.UserID)	}		return		respondError(w, http.StatusBadRequest, "invalid request body")	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {	}		AmountUSD string `json:"amount_usd"`		UserID    string `json:"user_id"`	var req struct {	}		return		respondError(w, http.StatusBadRequest, "invalid loan_id")	if err != nil {	loanID, err := uuidFromCtx(r, "loanID")func (h *Handler) RepayLoan(w http.ResponseWriter, r *http.Request) {}	respond(w, http.StatusCreated, loan)	}		return		respondError(w, http.StatusBadRequest, err.Error())	if err != nil {	})		Currency:             req.Currency,		RequestedAmountUSD:   amount,		CollateralPositionID: posID,		UserID:               userID,	loan, err := h.LoanSvc.RequestLoan(service.LoanRequest{	}		return		respondError(w, http.StatusBadRequest, "invalid requested_amount_usd")	if err != nil {	amount, err := decimal.NewFromString(req.RequestedAmountUSD)	}		return		respondError(w, http.StatusBadRequest, "invalid collateral_position_id")	if err != nil {	posID, err := uuid.Parse(req.CollateralPositionID)	}		return		respondError(w, http.StatusBadRequest, "invalid user_id")	if err != nil {	userID, err := uuid.Parse(req.UserID)	}		return		respondError(w, http.StatusBadRequest, "invalid request body")	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {	}		Currency             string `json:"currency"`		RequestedAmountUSD   string `json:"requested_amount_usd"`		CollateralPositionID string `json:"collateral_position_id"`		UserID               string `json:"user_id"`	var req struct {func (h *Handler) RequestLoan(w http.ResponseWriter, r *http.Request) {// ─── Loans ───────────────────────────────────────────────────────────────────}	respond(w, http.StatusOK, position)	}		return		respondError(w, http.StatusNotFound, "position not found")	if err != nil {	position, err := h.CollateralSvc.GetPosition(posID)	}		return		respondError(w, http.StatusBadRequest, "invalid position_id")	if err != nil {	posID, err := uuidFromCtx(r, "positionID")func (h *Handler) GetPosition(w http.ResponseWriter, r *http.Request) {}	respond(w, http.StatusOK, positions)	}		return		respondError(w, http.StatusInternalServerError, err.Error())	if err != nil {	positions, err := h.CollateralSvc.GetPositions(userID)	}		return		respondError(w, http.StatusBadRequest, "user_id query param required")	if err != nil {	userID, err := uuid.Parse(userIDStr)	userIDStr := r.URL.Query().Get("user_id")func (h *Handler) GetPositions(w http.ResponseWriter, r *http.Request) {}	respond(w, http.StatusOK, position)	}		return		respondError(w, http.StatusBadRequest, err.Error())	if err != nil {	position, err := h.CollateralSvc.Withdraw(posID, amount)	}		return		respondError(w, http.StatusBadRequest, "invalid amount")	if err != nil {	amount, err := decimal.NewFromString(req.Amount)	}		return		respondError(w, http.StatusBadRequest, "invalid position_id")	if err != nil {	posID, err := uuid.Parse(req.PositionID)	}		return		respondError(w, http.StatusBadRequest, "invalid request body")	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {	}		Amount     string `json:"amount"`		PositionID string `json:"position_id"`	var req struct {func (h *Handler) WithdrawCollateral(w http.ResponseWriter, r *http.Request) {}	})		"created_at": position.CreatedAt,		"status":    position.Status,		"value_usd": position.Amount.Mul(feed.PriceUSD).Round(2).String(),		"amount":    position.Amount.String(),		"asset":     position.Asset,		"user_id":   position.UserID,		"id":        position.ID,	respond(w, http.StatusCreated, map[string]interface{}{	feed, _ := h.Oracle.GetPrice(position.Asset)	// Enrich with USD value	}		return		respondError(w, http.StatusBadRequest, err.Error())	if err != nil {	})		Amount: amount,		Asset:  req.Asset,		UserID: userID,	position, err := h.CollateralSvc.Deposit(service.DepositRequest{	}		return		respondError(w, http.StatusBadRequest, "invalid amount")	if err != nil {	amount, err := decimal.NewFromString(req.Amount)	}		return		respondError(w, http.StatusBadRequest, "invalid user_id")	if err != nil {	userID, err := uuid.Parse(req.UserID)	}		return		respondError(w, http.StatusBadRequest, "invalid request body")	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {	}		Amount string `json:"amount"`		Asset  string `json:"asset"`		UserID string `json:"user_id"`	var req struct {func (h *Handler) DepositCollateral(w http.ResponseWriter, r *http.Request) {// ─── Collateral ──────────────────────────────────────────────────────────────}	respond(w, http.StatusOK, user)	}		return		respondError(w, http.StatusNotFound, "user not found")	if err != nil {	user, err := h.UserSvc.GetUser(userID)	}		return		respondError(w, http.StatusBadRequest, "invalid user_id")	if err != nil {	userID, err := uuidFromCtx(r, "userID")func (h *Handler) GetUser(w http.ResponseWriter, r *http.Request) {}	respond(w, http.StatusCreated, user)	}		return		respondError(w, http.StatusInternalServerError, err.Error())	if err != nil {	user, err := h.UserSvc.CreateUser(req.Email, req.FullName)	}		return		respondError(w, http.StatusBadRequest, "email and full_name are required")	if req.Email == "" || req.FullName == "" {	}		return		respondError(w, http.StatusBadRequest, "invalid request body")	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {	}		FullName string `json:"full_name"`		Email    string `json:"email"`	var req struct {func (h *Handler) CreateUser(w http.ResponseWriter, r *http.Request) {// ─── Users ───────────────────────────────────────────────────────────────────}	})		"circuit_breakers": cbState,		"status":           "ok",	respond(w, http.StatusOK, map[string]interface{}{	cbState := h.Store.GetCircuitBreakerState()func (h *Handler) Health(w http.ResponseWriter, r *http.Request) {// ─── Health ──────────────────────────────────────────────────────────────────}	Store         *repository.InMemoryStore	Oracle        *oracle.PriceOracle	RiskEngine    *risk.Engine	LoanSvc       *service.LoanService	CollateralSvc *service.CollateralService	UserSvc       *service.UserServicetype Handler struct {// Handler aggregates all HTTP handlers.)	"github.com/shopspring/decimal"	"github.com/google/uuid"	"github.com/go-chi/chi/v5"	"github.com/cryptolend/protocol-defi/internal/service"	"github.com/cryptolend/protocol-defi/internal/risk"	"github.com/cryptolend/protocol-defi/internal/repository"	"github.com/cryptolend/protocol-defi/internal/oracle"