package repository
package repository

import (
	"sync"
	"time"













































































































































































































































































































}	return total	}		}			total = total.Add(l.OutstandingUSD).Add(l.AccruedInterestUSD)		if l.CollateralPositionID == posID && l.Status == domain.LoanActive {	for _, l := range s.loans {	total := decimal.Zero	defer s.mu.RUnlock()	s.mu.RLock()func (s *InMemoryStore) TotalOutstandingForPosition(posID uuid.UUID) decimal.Decimal {// TotalOutstandingForPosition sums outstanding USD for all active loans on a position.// ─── Helper ──────────────────────────────────────────────────────────────────}	return e.Messagefunc (e *RepoError) Error() string {}	Message stringtype RepoError struct {)	ErrDuplicate = &RepoError{Message: "duplicate entry"}	ErrNotFound  = &RepoError{Message: "not found"}var (// ─── Error Sentinels ─────────────────────────────────────────────────────────}	return result	}		result[k] = v	for k, v := range s.circuitBreakers {	result := make(map[string]bool, len(s.circuitBreakers))	defer s.mu.RUnlock()	s.mu.RLock()func (s *InMemoryStore) GetCircuitBreakerState() map[string]bool {}	s.circuitBreakers[feature] = enabled	defer s.mu.Unlock()	s.mu.Lock()func (s *InMemoryStore) SetFeatureEnabled(feature string, enabled bool) {}	return ok && enabled	enabled, ok := s.circuitBreakers[feature]	defer s.mu.RUnlock()	s.mu.RLock()func (s *InMemoryStore) IsFeatureEnabled(feature string) bool {// ─── Circuit Breaker ─────────────────────────────────────────────────────────}	return e, nil	}		return nil, ErrNotFound	if !ok {	e, ok := s.liquidationEvents[id]	defer s.mu.RUnlock()	s.mu.RLock()func (s *InMemoryStore) GetLiquidationEvent(id uuid.UUID) (*domain.LiquidationEvent, error) {}	return result, nil	}		}			result = append(result, e)		if ok && loan.UserID == userID {		loan, ok := s.loans[e.LoanID]	for _, e := range s.liquidationEvents {	var result []*domain.LiquidationEvent	defer s.mu.RUnlock()	s.mu.RLock()func (s *InMemoryStore) GetLiquidationsByUser(userID uuid.UUID) ([]*domain.LiquidationEvent, error) {}	return nil	s.liquidationEvents[e.ID] = e	}		return ErrNotFound	if _, ok := s.liquidationEvents[e.ID]; !ok {	defer s.mu.Unlock()	s.mu.Lock()func (s *InMemoryStore) UpdateLiquidationEvent(e *domain.LiquidationEvent) error {}	return nil	s.liquidationEvents[e.ID] = e	e.CreatedAt = time.Now().UTC()	e.ID = uuid.New()	}		}			return ErrDuplicate		if existing.IdempotencyKey == e.IdempotencyKey {	for _, existing := range s.liquidationEvents {	// Idempotency check	defer s.mu.Unlock()	s.mu.Lock()func (s *InMemoryStore) CreateLiquidationEvent(e *domain.LiquidationEvent) error {// ─── Liquidation Events ─────────────────────────────────────────────────────}	return result, nil	}		}			result = append(result, t)		if t.UserID == userID {	for _, t := range s.transactions {	var result []domain.Transaction	defer s.mu.RUnlock()	s.mu.RLock()func (s *InMemoryStore) GetTransactionsByUser(userID uuid.UUID) ([]domain.Transaction, error) {}	return nil	s.transactions = append(s.transactions, *t)	t.CreatedAt = time.Now().UTC()	t.ID = uuid.New()	defer s.mu.Unlock()	s.mu.Lock()func (s *InMemoryStore) RecordTransaction(t *domain.Transaction) error {// ─── Transactions ────────────────────────────────────────────────────────────}	return result, nil	}		}			result = append(result, l)		if l.Status == domain.LoanActive {	for _, l := range s.loans {	var result []*domain.Loan	defer s.mu.RUnlock()	s.mu.RLock()func (s *InMemoryStore) GetAllActiveLoans() ([]*domain.Loan, error) {}	return result, nil	}		}			result = append(result, l)		if l.CollateralPositionID == posID && l.Status == domain.LoanActive {	for _, l := range s.loans {	var result []*domain.Loan	defer s.mu.RUnlock()	s.mu.RLock()func (s *InMemoryStore) GetActiveLoansByPosition(posID uuid.UUID) ([]*domain.Loan, error) {}	return result, nil	}		}			result = append(result, l)		if l.UserID == userID {	for _, l := range s.loans {	var result []*domain.Loan	defer s.mu.RUnlock()	s.mu.RLock()func (s *InMemoryStore) GetLoansByUser(userID uuid.UUID) ([]*domain.Loan, error) {}	return nil	s.loans[l.ID] = l	l.UpdatedAt = time.Now().UTC()	}		return ErrNotFound	if _, ok := s.loans[l.ID]; !ok {	defer s.mu.Unlock()	s.mu.Lock()func (s *InMemoryStore) UpdateLoan(l *domain.Loan) error {}	return l, nil	}		return nil, ErrNotFound	if !ok {	l, ok := s.loans[id]	defer s.mu.RUnlock()	s.mu.RLock()func (s *InMemoryStore) GetLoan(id uuid.UUID) (*domain.Loan, error) {}	return nil	s.loans[l.ID] = l	l.UpdatedAt = l.CreatedAt	l.CreatedAt = time.Now().UTC()	l.ID = uuid.New()	defer s.mu.Unlock()	s.mu.Lock()func (s *InMemoryStore) CreateLoan(l *domain.Loan) error {// ─── Loans ───────────────────────────────────────────────────────────────────}	return result, nil	}		}			result = append(result, p)		if p.UserID == userID {	for _, p := range s.collateralPositions {	var result []*domain.CollateralPosition	defer s.mu.RUnlock()	s.mu.RLock()func (s *InMemoryStore) GetPositionsByUser(userID uuid.UUID) ([]*domain.CollateralPosition, error) {}	return nil	s.collateralPositions[p.ID] = p	p.UpdatedAt = time.Now().UTC()	}		return ErrNotFound	if _, ok := s.collateralPositions[p.ID]; !ok {	defer s.mu.Unlock()	s.mu.Lock()func (s *InMemoryStore) UpdatePosition(p *domain.CollateralPosition) error {}	return p, nil	}		return nil, ErrNotFound	if !ok {	p, ok := s.collateralPositions[id]	defer s.mu.RUnlock()	s.mu.RLock()func (s *InMemoryStore) GetPosition(id uuid.UUID) (*domain.CollateralPosition, error) {}	return nil	s.collateralPositions[p.ID] = p	p.UpdatedAt = p.CreatedAt	p.CreatedAt = time.Now().UTC()	p.ID = uuid.New()	defer s.mu.Unlock()	s.mu.Lock()func (s *InMemoryStore) CreatePosition(p *domain.CollateralPosition) error {// ─── Collateral Positions ────────────────────────────────────────────────────}	return u, nil	}		return nil, ErrNotFound	if !ok {	u, ok := s.users[id]	defer s.mu.RUnlock()	s.mu.RLock()func (s *InMemoryStore) GetUser(id uuid.UUID) (*domain.User, error) {}	return nil	s.users[u.ID] = u	u.UpdatedAt = u.CreatedAt	u.CreatedAt = time.Now().UTC()	u.ID = uuid.New()	defer s.mu.Unlock()	s.mu.Lock()func (s *InMemoryStore) CreateUser(u *domain.User) error {// ─── Users ───────────────────────────────────────────────────────────────────}	}		},			"WITHDRAWAL":  true,			"LIQUIDATION": true,			"LENDING":     true,		circuitBreakers: map[string]bool{		liquidationEvents:   make(map[uuid.UUID]*domain.LiquidationEvent),		transactions:        make([]domain.Transaction, 0),		loans:               make(map[uuid.UUID]*domain.Loan),		collateralPositions: make(map[uuid.UUID]*domain.CollateralPosition),		wallets:             make(map[uuid.UUID]*domain.Wallet),		users:               make(map[uuid.UUID]*domain.User),	return &InMemoryStore{func NewInMemoryStore() *InMemoryStore {// NewInMemoryStore creates an initialized store.}	circuitBreakers     map[string]bool // feature -> enabled	liquidationEvents   map[uuid.UUID]*domain.LiquidationEvent	transactions        []domain.Transaction	loans               map[uuid.UUID]*domain.Loan	collateralPositions map[uuid.UUID]*domain.CollateralPosition	wallets             map[uuid.UUID]*domain.Wallet	users               map[uuid.UUID]*domain.User	mu                  sync.RWMutextype InMemoryStore struct {// In production, this would be backed by PostgreSQL via pgx.// InMemoryStore is a thread-safe in-memory repository for the MVP.)	"github.com/shopspring/decimal"	"github.com/google/uuid"	"github.com/cryptolend/protocol-defi/internal/domain"