package api
package main

import (





























































































































}	log.Println("[Server] Stopped")	}		log.Fatalf("[Server] Fatal: %v", err)	if err := srv.ListenAndServe(); err != http.ErrServerClosed {		cfg.MaxLTV.String(), cfg.LiquidationThreshold.String(), cfg.LiquidationPenalty.String())	log.Printf("[Server] Risk params: MaxLTV=%s, LiquidationThreshold=%s, Penalty=%s",	log.Printf("[Server] Starting CryptoLend API on port %s", cfg.Port)	}()		}			log.Fatalf("[Server] Shutdown error: %v", err)		if err := srv.Shutdown(shutdownCtx); err != nil {		defer shutdownCancel()		shutdownCtx, shutdownCancel := context.WithTimeout(context.Background(), 15*time.Second)		cancel()		log.Println("[Server] Shutting down...")		<-sigCh		signal.Notify(sigCh, syscall.SIGINT, syscall.SIGTERM)		sigCh := make(chan os.Signal, 1)	go func() {	// Graceful shutdown	}		IdleTimeout:  60 * time.Second,		WriteTimeout: 10 * time.Second,		ReadTimeout:  10 * time.Second,		Handler:      r,		Addr:         ":" + cfg.Port,	srv := &http.Server{	// ── HTTP Server ──	go liquidationEngine.Start(ctx)	go priceOracle.StartSimulation(ctx)	ctx, cancel := context.WithCancel(context.Background())	// ── Start background services ──	r.Post("/v1/admin/set-price", h.SetPrice)	r.Post("/v1/admin/circuit-breaker", h.ToggleCircuitBreaker)	// Admin	r.Get("/v1/liquidations/{liquidationID}", h.GetLiquidation)	r.Get("/v1/liquidations", h.GetLiquidations)	// Liquidations	r.Get("/v1/oracle/prices/{asset}", h.GetAssetPrice)	r.Get("/v1/oracle/prices", h.GetPrices)	// Oracle	r.Get("/v1/risk/positions", h.GetRiskPositions)	// Risk	r.Get("/v1/loans/{loanID}/ltv", h.GetLoanLTV)	r.Get("/v1/loans/{loanID}", h.GetLoan)	r.Get("/v1/loans", h.GetLoans)	r.Post("/v1/loans/{loanID}/repay", h.RepayLoan)	r.Post("/v1/loans", h.RequestLoan)	// Loans	r.Get("/v1/collateral/positions/{positionID}", h.GetPosition)	r.Get("/v1/collateral/positions", h.GetPositions)	r.Post("/v1/collateral/withdraw", h.WithdrawCollateral)	r.Post("/v1/collateral/deposit", h.DepositCollateral)	// Collateral	r.Get("/v1/users/{userID}", h.GetUser)	r.Post("/v1/users", h.CreateUser)	// Users	r.Get("/health", h.Health)	// Routes	r.Use(rateLimiter.Limit)	r.Use(middleware.RequestLogger)	r.Use(middleware.Recoverer)	rateLimiter := middleware.NewRateLimiter(100, time.Minute)	// Middleware	r := chi.NewRouter()	// ── Router ──	liquidationEngine := service.NewLiquidationEngine(cfg, store, priceOracle, riskEngine)	// ── Initialize liquidation engine ──	}		Store:         store,		Oracle:        priceOracle,		RiskEngine:    riskEngine,		LoanSvc:       loanSvc,		CollateralSvc: collateralSvc,		UserSvc:       userSvc,	h := &handler.Handler{	loanSvc := service.NewLoanService(cfg, store, priceOracle, riskEngine)	collateralSvc := service.NewCollateralService(store, priceOracle, riskEngine)	userSvc := service.NewUserService(store)	riskEngine := risk.NewEngine(cfg, store, priceOracle)	priceOracle := oracle.NewPriceOracle(cfg)	store := repository.NewInMemoryStore()	// ── Initialize dependencies ──	cfg := config.Load()func main() {)	"github.com/go-chi/chi/v5"	"github.com/cryptolend/protocol-defi/internal/service"	"github.com/cryptolend/protocol-defi/internal/risk"	"github.com/cryptolend/protocol-defi/internal/repository"	"github.com/cryptolend/protocol-defi/internal/oracle"	"github.com/cryptolend/protocol-defi/internal/middleware"	"github.com/cryptolend/protocol-defi/internal/handler"	"github.com/cryptolend/protocol-defi/internal/config"	"time"	"syscall"	"os/signal"	"os"	"net/http"	"log"	"context"