package service
package service

import (
	"context"
	"fmt"
	"log"
	"time"









































































































































































































































































}	return price.Mul(decimal.NewFromInt(1).Sub(slippagePct))	slippagePct := decimal.NewFromInt(int64(bps)).Div(decimal.NewFromInt(10000))func applySlippage(price decimal.Decimal, bps int) decimal.Decimal {// E.g., 50 BPS = 0.5% slippage.// applySlippage reduces the price by the given basis points.}	}		})			AmountUSD: event.ReturnedToUserUSD,			Amount:    event.ReturnedToUserUSD,			Asset:     "USD",			Type:      domain.TxLiquidationReturn,			LoanID:    &loanID,			UserID:    loan.UserID,		_ = le.store.RecordTransaction(&domain.Transaction{	if event.ReturnedToUserUSD.IsPositive() {	// 3. Return excess to user	}		})			AmountUSD: event.PenaltyUSD,			Amount:    event.PenaltyUSD,			Asset:     "USD",			Type:      domain.TxLiquidationPenalty,			LoanID:    &loanID,			UserID:    loan.UserID,		_ = le.store.RecordTransaction(&domain.Transaction{	if event.PenaltyUSD.IsPositive() {	// 2. Penalty	})		ReferencePrice: salePrice,		AmountUSD:      event.SaleProceedsUSD,		Amount:         event.CollateralAmount,		Asset:          position.Asset,		Type:           domain.TxLiquidationSale,		PositionID:     &posID,		LoanID:         &loanID,		UserID:         loan.UserID,	_ = le.store.RecordTransaction(&domain.Transaction{	// 1. Collateral sale	posID := position.ID	loanID := loan.ID) {	salePrice decimal.Decimal,	event *domain.LiquidationEvent,	position *domain.CollateralPosition,	loan *domain.Loan,func (le *LiquidationEngine) recordLiquidationTransactions(// recordLiquidationTransactions creates the audit trail for a liquidation.}	return nil	)		returnedToUser.Round(2).String(),		actualPenalty.Round(2).String(),		debtRepaid.Round(2).String(),		salePricePerUnit.String(),		collateralAmount.InexactFloat64(), position.Asset,		loan.ID,		"repaid $%s, penalty $%s, returned $%s",	log.Printf("[Liquidation] COMPLETED for loan %s — sold %.6f %s @ $%s, "+	_ = le.store.UpdateLiquidationEvent(event)	event.CompletedAt = &now	event.Status = domain.LiquidationCompleted	now := time.Now().UTC()	_ = le.store.UpdateLoan(loan)	loan.Status = domain.LoanLiquidated	loan.AccruedInterestUSD = decimal.Zero	loan.OutstandingUSD = loan.OutstandingUSD.Sub(debtRepaid)	_ = le.store.UpdatePosition(position)	position.Status = domain.PositionLiquidated	position.LockedAmount = decimal.Zero	position.Amount = decimal.Zero	// ── Step 5: Update final states ──	le.recordLiquidationTransactions(loan, position, event, salePricePerUnit)	// ── Step 4: Record transactions ──	_ = le.store.UpdatePosition(position)	position.Status = domain.PositionLiquidating	// Mark position as liquidating	_ = le.store.UpdateLiquidationEvent(event)	event.Status = domain.LiquidationExecuting	// ── Step 3: Execute — mark as EXECUTING ──	}		return fmt.Errorf("failed to create liquidation event: %w", err)		}			return nil			log.Printf("[Liquidation] Duplicate event for loan %s, skipping", loan.ID)		if err == repository.ErrDuplicate {	if err := le.store.CreateLiquidationEvent(event); err != nil {	}		IdempotencyKey:       idempotencyKey,		Status:               domain.LiquidationPending,		ReturnedToUserUSD:    returnedToUser.Round(2),		PenaltyUSD:           actualPenalty.Round(2),		DebtRepaidUSD:        debtRepaid.Round(2),		SaleProceedsUSD:      saleProceeds.Round(2),		SalePriceUSD:         salePricePerUnit,		CollateralAmount:     collateralAmount,		TriggerLTV:           ltv.CurrentLTV,		CollateralPositionID: position.ID,		LoanID:               loan.ID,	event := &domain.LiquidationEvent{	// ── Step 2: Create liquidation event (PENDING) ──	}		}			actualPenalty = decimal.Zero			debtRepaid = saleProceeds			// Can't even cover debt fully		} else {			actualPenalty = saleProceeds.Sub(totalDebt)		if saleProceeds.GreaterThan(totalDebt) {		// Not enough to cover debt + penalty — penalty is reduced first	} else if saleProceeds.LessThan(totalOwed) {		returnedToUser = saleProceeds.Sub(totalOwed)		// Surplus goes back to user	if saleProceeds.GreaterThan(totalOwed) {	actualPenalty := penalty	debtRepaid := totalDebt	returnedToUser := decimal.Zero	totalOwed := totalDebt.Add(penalty)	penalty := totalDebt.Mul(le.cfg.LiquidationPenalty)	totalDebt := loan.OutstandingUSD.Add(loan.AccruedInterestUSD)	saleProceeds := collateralAmount.Mul(salePricePerUnit)	salePricePerUnit := applySlippage(priceFeed.PriceUSD, le.cfg.SlippageBPS)	collateralAmount := position.Amount	// ── Step 1: Calculate liquidation amounts ──	}		return fmt.Errorf("no price for asset %s", position.Asset)	if !ok {	priceFeed, ok := le.oracle.GetPrice(position.Asset)	}		return nil		log.Printf("[Liquidation] Position %s already in state %s, skipping", position.ID, position.Status)	if position.Status == domain.PositionLiquidating || position.Status == domain.PositionLiquidated {	// Already being liquidated?	}		return fmt.Errorf("position lookup failed: %w", err)	if err != nil {	position, err := le.store.GetPosition(loan.CollateralPositionID)	idempotencyKey := fmt.Sprintf("liq_%s_%d", loan.ID.String(), time.Now().UTC().UnixMilli())	// Idempotency key: prevents double-liquidation of the same loanfunc (le *LiquidationEngine) executeLiquidation(loan *domain.Loan, ltv *domain.LTVResult) error {//  7. Mark liquidation event as COMPLETED//  6. Mark loan as LIQUIDATED, position as LIQUIDATED//  5. Return excess to user (if any)//  4. Calculate: debt_to_repay + penalty//  3. Simulate collateral sale (market price - slippage)//  2. Mark position as LIQUIDATING//  1. Create idempotent liquidation event (PENDING)// Steps://// executeLiquidation performs the full liquidation flow for a single loan.}	}		}			}				log.Printf("[Liquidation] FAILED for loan %s: %v", loan.ID, err)			if err := le.executeLiquidation(loan, ltvResult); err != nil {				le.cfg.LiquidationThreshold.InexactFloat64())				loan.ID, ltvResult.CurrentLTV.InexactFloat64(),			log.Printf("[Liquidation] TRIGGERED for loan %s — LTV=%.4f (threshold=%.4f)",		if ltvResult.Status == domain.LTVStatusLiquidating {		}			continue			log.Printf("[Liquidation] Error calculating LTV for loan %s: %v", loan.ID, err)		if err != nil {		ltvResult, err := le.risk.CalculateLTV(loan.ID)	for _, loan := range loans {	}		return		log.Printf("[Liquidation] Error fetching loans: %v", err)	if err != nil {	loans, err := le.store.GetAllActiveLoans()	}		return		log.Println("[Liquidation] Circuit breaker OPEN — skipping scan")	if !le.store.IsFeatureEnabled("LIQUIDATION") {	// Check circuit breakerfunc (le *LiquidationEngine) scanAndLiquidate() {// scanAndLiquidate checks all positions and triggers liquidation where needed.}	}		}			le.scanAndLiquidate()		case <-ticker.C:			return			log.Println("[Liquidation] Engine stopping")		case <-ctx.Done():		select {	for {	log.Printf("[Liquidation] Engine started, poll interval=%ds", le.cfg.LiquidationPollIntervalSec)	defer ticker.Stop()	ticker := time.NewTicker(time.Duration(le.cfg.LiquidationPollIntervalSec) * time.Second)func (le *LiquidationEngine) Start(ctx context.Context) {// Start begins the liquidation monitoring loop.}	}		risk:   riskEngine,		oracle: oracle,		store:  store,		cfg:    cfg,	return &LiquidationEngine{) *LiquidationEngine {	riskEngine *risk.Engine,	oracle *oracle.PriceOracle,	store *repository.InMemoryStore,	cfg *config.Config,func NewLiquidationEngine(// NewLiquidationEngine creates a new engine.}	risk   *risk.Engine	oracle *oracle.PriceOracle	store  *repository.InMemoryStore	cfg    *config.Configtype LiquidationEngine struct {// double liquidation of the same loan.// Idempotency: uses loan_id + timestamp as idempotency key to prevent////  4. Update loan and position statuses//  3. Execute: sell collateral → repay debt → apply penalty → return excess//  2. For each: create idempotent liquidation event//  1. Scan all active loans for LTV >= liquidation threshold// Liquidation Flow://// LiquidationEngine monitors positions and executes liquidations.)	"github.com/shopspring/decimal"	"github.com/cryptolend/protocol-defi/internal/risk"	"github.com/cryptolend/protocol-defi/internal/repository"	"github.com/cryptolend/protocol-defi/internal/oracle"	"github.com/cryptolend/protocol-defi/internal/domain"	"github.com/cryptolend/protocol-defi/internal/config"