package config
package config

import (
	"os"

















































































}	return i	}		return fallback	if err != nil {	i, err := strconv.Atoi(v)	}		return fallback	if v == "" {	v := os.Getenv(key)func intEnv(key string, fallback int) int {}	return d	}		d, _ = decimal.NewFromString(fallback)	if err != nil {	d, err := decimal.NewFromString(v)	v := envOrDefault(key, fallback)func decimalEnv(key, fallback string) decimal.Decimal {}	return fallback	}		return v	if v := os.Getenv(key); v != "" {func envOrDefault(key, fallback string) string {}	}		SlippageBPS:                intEnv("SLIPPAGE_BPS", 50), // 0.5%		LiquidationPollIntervalSec: intEnv("LIQUIDATION_POLL_INTERVAL_SEC", 10),		DefaultBTCPriceUSD:    decimalEnv("DEFAULT_BTC_PRICE_USD", "42500.00"),		OraclePollIntervalSec: intEnv("ORACLE_POLL_INTERVAL_SEC", 30),		DefaultInterestRate: decimalEnv("DEFAULT_INTEREST_RATE", "0.05"),		CriticalThreshold:    decimalEnv("CRITICAL_THRESHOLD", "0.60"),		WarningThreshold:     decimalEnv("WARNING_THRESHOLD", "0.40"),		LiquidationPenalty:   decimalEnv("LIQUIDATION_PENALTY", "0.10"),		LiquidationThreshold: decimalEnv("LIQUIDATION_THRESHOLD", "0.70"),		MaxLTV:               decimalEnv("MAX_LTV", "0.50"),		DatabaseURL: envOrDefault("DATABASE_URL", "postgres://localhost:5432/cryptolend?sslmode=disable"),		Port:        envOrDefault("PORT", "8080"),	return &Config{func Load() *Config {// Load reads configuration from environment variables with sensible defaults.}	SlippageBPS                int // Basis points slippage for simulated market sale	LiquidationPollIntervalSec int	// Liquidation Engine	DefaultBTCPriceUSD    decimal.Decimal	OraclePollIntervalSec int	// Oracle	DefaultInterestRate decimal.Decimal // Annual interest rate (e.g., 0.05 = 5%)	// Interest	CriticalThreshold    decimal.Decimal // LTV threshold for critical status (e.g., 0.60 = 60%)	WarningThreshold     decimal.Decimal // LTV threshold for warning status (e.g., 0.40 = 40%)	LiquidationPenalty   decimal.Decimal // Penalty applied on liquidation (e.g., 0.10 = 10%)	LiquidationThreshold decimal.Decimal // LTV at which liquidation triggers (e.g., 0.70 = 70%)	MaxLTV               decimal.Decimal // Maximum LTV allowed at loan origination (e.g., 0.50 = 50%)	// Risk Parameters	DatabaseURL string	// Database	Port string	// Servertype Config struct {// Config holds all application configuration.)	"github.com/shopspring/decimal"	"strconv"