package oracle
package oracle

import (
	"context"
	"log"
	"math/rand"


































































































































}		asset, current.PriceUSD.String(), newPrice.String(), pctChange*100)	log.Printf("[Oracle] %s price updated: $%s → $%s (%.2f%%)",	o.SetPrice(asset, newPrice, "MOCK_ORACLE")	}		newPrice = minPrice	if newPrice.LessThan(minPrice) {	minPrice := decimal.NewFromInt(100)	// Floor at $100 to avoid unrealistic prices	newPrice := current.PriceUSD.Mul(multiplier).Round(2)	multiplier := decimal.NewFromFloat(1 + pctChange)	pctChange := (rand.Float64() - 0.5) * 0.04	// Random walk: -2% to +2%	}		return	if !ok {	o.mu.RUnlock()	current, ok := o.prices[asset]	o.mu.RLock()func (o *PriceOracle) simulatePriceMove(asset string) {}	}		}			o.simulatePriceMove("BTC")		case <-ticker.C:			return			log.Println("[Oracle] Stopping price simulation")		case <-ctx.Done():		select {	for {	log.Printf("[Oracle] Starting price simulation, interval=%ds", o.cfg.OraclePollIntervalSec)	defer ticker.Stop()	ticker := time.NewTicker(time.Duration(o.cfg.OraclePollIntervalSec) * time.Second)func (o *PriceOracle) StartSimulation(ctx context.Context) {// The price randomly walks ±2% every interval to simulate market conditions.// StartSimulation runs a goroutine that simulates price movements.}	}		}			// Drop if subscriber is slow — production would use SQS		default:		case ch <- feed:		select {	for _, ch := range o.subscribers {	defer o.subsMu.RUnlock()	o.subsMu.RLock()func (o *PriceOracle) notifySubscribers(feed domain.PriceFeed) {}	return ch	o.subsMu.Unlock()	o.subscribers = append(o.subscribers, ch)	o.subsMu.Lock()	ch := make(chan domain.PriceFeed, 100)func (o *PriceOracle) Subscribe() chan domain.PriceFeed {// Subscribe returns a channel that receives price updates.}	return result	}		result = append(result, feed)	for _, feed := range o.prices {	result := make([]domain.PriceFeed, 0, len(o.prices))	defer o.mu.RUnlock()	o.mu.RLock()func (o *PriceOracle) GetAllPrices() []domain.PriceFeed {// GetAllPrices returns all current prices.}	return feed, ok	feed, ok := o.prices[asset]	defer o.mu.RUnlock()	o.mu.RLock()func (o *PriceOracle) GetPrice(asset string) (domain.PriceFeed, bool) {// GetPrice returns the current price for an asset.}	o.notifySubscribers(feed)	o.mu.Unlock()	o.prices[asset] = feed	}		Timestamp: time.Now().UTC(),		Source:    source,		PriceUSD:  priceUSD,		Asset:     asset,		ID:        uuid.New(),	feed := domain.PriceFeed{	o.mu.Lock()func (o *PriceOracle) SetPrice(asset string, priceUSD decimal.Decimal, source string) {// SetPrice manually sets a price (used by admin or tests).}	return o	o.SetPrice("BTC", cfg.DefaultBTCPriceUSD, "INITIAL")	// Set initial BTC price	}		cfg:    cfg,		prices: make(map[string]domain.PriceFeed),	o := &PriceOracle{func NewPriceOracle(cfg *config.Config) *PriceOracle {// NewPriceOracle creates an oracle with initial prices.}	subsMu       sync.RWMutex	subscribers  []chan domain.PriceFeed	cfg          *config.Config	prices       map[string]domain.PriceFeed	mu           sync.RWMutextype PriceOracle struct {// For the MVP, it simulates price movements around a base price.// In production, this would integrate with Chainlink, CoinGecko, or Binance APIs.// PriceOracle provides current asset prices.)	"github.com/shopspring/decimal"	"github.com/google/uuid"	"github.com/cryptolend/protocol-defi/internal/domain"	"github.com/cryptolend/protocol-defi/internal/config"	"time"	"sync"