package domain
package domain

import (
	"time"

	"github.com/google/uuid"















































































































































































}	PriceUpdatedAt       time.Time       `json:"price_updated_at"`	Status               LTVStatus       `json:"ltv_status"`	LiquidationThreshold decimal.Decimal `json:"liquidation_threshold"`	MaxLTV               decimal.Decimal `json:"max_ltv"`	CurrentLTV           decimal.Decimal `json:"current_ltv"`	LoanOutstandingUSD   decimal.Decimal `json:"loan_outstanding_usd"`	CollateralValueUSD   decimal.Decimal `json:"collateral_value_usd"`	CollateralAmount     decimal.Decimal `json:"collateral_amount"`	CollateralAsset      string          `json:"collateral_asset"`	LoanID               uuid.UUID       `json:"loan_id"`type LTVResult struct {// ─── LTV Calculation Result ──────────────────────────────────────────────────}	CompletedAt            *time.Time        `json:"completed_at,omitempty" db:"completed_at"`	CreatedAt              time.Time         `json:"created_at" db:"created_at"`	ErrorMessage           string            `json:"error_message,omitempty" db:"error_message"`	IdempotencyKey         string            `json:"idempotency_key" db:"idempotency_key"`	Status                 LiquidationStatus `json:"status" db:"status"`	ReturnedToUserUSD      decimal.Decimal   `json:"returned_to_user_usd" db:"returned_to_user_usd"`	PenaltyUSD             decimal.Decimal   `json:"penalty_usd" db:"penalty_usd"`	DebtRepaidUSD          decimal.Decimal   `json:"debt_repaid_usd" db:"debt_repaid_usd"`	SaleProceedsUSD        decimal.Decimal   `json:"sale_proceeds_usd" db:"sale_proceeds_usd"`	SalePriceUSD           decimal.Decimal   `json:"sale_price_usd" db:"sale_price_usd"`	CollateralAmount       decimal.Decimal   `json:"collateral_amount" db:"collateral_amount"`	TriggerLTV             decimal.Decimal   `json:"trigger_ltv" db:"trigger_ltv"`	CollateralPositionID   uuid.UUID         `json:"collateral_position_id" db:"collateral_position_id"`	LoanID                 uuid.UUID         `json:"loan_id" db:"loan_id"`	ID                     uuid.UUID         `json:"id" db:"id"`type LiquidationEvent struct {)	LiquidationFailed    LiquidationStatus = "FAILED"	LiquidationCompleted LiquidationStatus = "COMPLETED"	LiquidationExecuting LiquidationStatus = "EXECUTING"	LiquidationPending   LiquidationStatus = "PENDING"const (type LiquidationStatus string// ─── Liquidation Event ───────────────────────────────────────────────────────}	Timestamp time.Time       `json:"timestamp" db:"timestamp"`	Source    string          `json:"source" db:"source"`	PriceUSD  decimal.Decimal `json:"price_usd" db:"price_usd"`	Asset     string          `json:"asset" db:"asset"`	ID        uuid.UUID       `json:"id" db:"id"`type PriceFeed struct {// ─── Price Feed ──────────────────────────────────────────────────────────────}	CreatedAt      time.Time       `json:"created_at" db:"created_at"`	ReferencePrice decimal.Decimal `json:"reference_price" db:"reference_price"`	AmountUSD      decimal.Decimal `json:"amount_usd" db:"amount_usd"`	Amount         decimal.Decimal `json:"amount" db:"amount"`	Asset          string          `json:"asset" db:"asset"`	Type           TransactionType `json:"type" db:"type"`	PositionID     *uuid.UUID      `json:"position_id,omitempty" db:"position_id"`	LoanID         *uuid.UUID      `json:"loan_id,omitempty" db:"loan_id"`	UserID         uuid.UUID       `json:"user_id" db:"user_id"`	ID             uuid.UUID       `json:"id" db:"id"`type Transaction struct {)	TxInterestAccrual      TransactionType = "INTEREST_ACCRUAL"	TxLiquidationReturn    TransactionType = "LIQUIDATION_RETURN"	TxLiquidationPenalty   TransactionType = "LIQUIDATION_PENALTY"	TxLiquidationSale      TransactionType = "LIQUIDATION_SALE"	TxLoanRepayment        TransactionType = "LOAN_REPAYMENT"	TxLoanDisbursement     TransactionType = "LOAN_DISBURSEMENT"	TxCollateralWithdrawal TransactionType = "COLLATERAL_WITHDRAWAL"	TxCollateralDeposit    TransactionType = "COLLATERAL_DEPOSIT"const (type TransactionType string// ─── Transaction ─────────────────────────────────────────────────────────────}	UpdatedAt              time.Time       `json:"updated_at" db:"updated_at"`	CreatedAt              time.Time       `json:"created_at" db:"created_at"`	LTVSnapshot            decimal.Decimal `json:"ltv_snapshot" db:"ltv_snapshot"`	Status                 LoanStatus      `json:"status" db:"status"`	DisbursementCurrency   string          `json:"disbursement_currency" db:"disbursement_currency"`	AccruedInterestUSD     decimal.Decimal `json:"accrued_interest_usd" db:"accrued_interest_usd"`	InterestRateAnnual     decimal.Decimal `json:"interest_rate_annual" db:"interest_rate_annual"`	OutstandingUSD         decimal.Decimal `json:"outstanding_usd" db:"outstanding_usd"`	PrincipalUSD           decimal.Decimal `json:"principal_usd" db:"principal_usd"`	CollateralPositionID   uuid.UUID       `json:"collateral_position_id" db:"collateral_position_id"`	UserID                 uuid.UUID       `json:"user_id" db:"user_id"`	ID                     uuid.UUID       `json:"id" db:"id"`type Loan struct {)	LoanDefaulted  LoanStatus = "DEFAULTED"	LoanLiquidated LoanStatus = "LIQUIDATED"	LoanRepaid     LoanStatus = "REPAID"	LoanActive     LoanStatus = "ACTIVE"const (type LoanStatus string// ─── Loan ────────────────────────────────────────────────────────────────────}	UpdatedAt    time.Time       `json:"updated_at" db:"updated_at"`	CreatedAt    time.Time       `json:"created_at" db:"created_at"`	Status       PositionStatus  `json:"status" db:"status"`	LockedAmount decimal.Decimal `json:"locked_amount" db:"locked_amount"`	Amount       decimal.Decimal `json:"amount" db:"amount"`	Asset        string          `json:"asset" db:"asset"`	UserID       uuid.UUID       `json:"user_id" db:"user_id"`	ID           uuid.UUID       `json:"id" db:"id"`type CollateralPosition struct {)	PositionClosed      PositionStatus = "CLOSED"	PositionLiquidated  PositionStatus = "LIQUIDATED"	PositionLiquidating PositionStatus = "LIQUIDATING"	PositionActive      PositionStatus = "ACTIVE"const (type PositionStatus string// ─── Collateral Position ─────────────────────────────────────────────────────}	UpdatedAt time.Time       `json:"updated_at" db:"updated_at"`	CreatedAt time.Time       `json:"created_at" db:"created_at"`	Balance   decimal.Decimal `json:"balance" db:"balance"`	Address   string          `json:"address" db:"address"`	Asset     string          `json:"asset" db:"asset"`	UserID    uuid.UUID       `json:"user_id" db:"user_id"`	ID        uuid.UUID       `json:"id" db:"id"`type Wallet struct {// ─── Wallet ──────────────────────────────────────────────────────────────────}	UpdatedAt time.Time `json:"updated_at" db:"updated_at"`	CreatedAt time.Time `json:"created_at" db:"created_at"`	Status    string    `json:"status" db:"status"`	KYCStatus KYCStatus `json:"kyc_status" db:"kyc_status"`	FullName  string    `json:"full_name" db:"full_name"`	Email     string    `json:"email" db:"email"`	ID        uuid.UUID `json:"id" db:"id"`type User struct {)	KYCRejected KYCStatus = "REJECTED"	KYCApproved KYCStatus = "APPROVED"	KYCPending  KYCStatus = "PENDING"const (type KYCStatus string// ─── User ────────────────────────────────────────────────────────────────────)	LTVStatusLiquidating LTVStatus = "LIQUIDATING" // LTV >= 70%	LTVStatusCritical    LTVStatus = "CRITICAL"    // 60% <= LTV < 70%	LTVStatusWarning     LTVStatus = "WARNING"     // 40% <= LTV < 60%	LTVStatusSafe        LTVStatus = "SAFE"        // LTV < 40%const (type LTVStatus string// ─── LTV Status Classification ──────────────────────────────────────────────)	"github.com/shopspring/decimal"