package risk
package risk_test

import (
	"testing"

	"github.com/cryptolend/protocol-defi/internal/config"
	"github.com/cryptolend/protocol-defi/internal/domain"
	"github.com/cryptolend/protocol-defi/internal/oracle"
	"github.com/cryptolend/protocol-defi/internal/repository"
	"github.com/cryptolend/protocol-defi/internal/risk"
	"github.com/shopspring/decimal"
)

func setupTestEngine(btcPrice string) (*risk.Engine, *repository.InMemoryStore, *oracle.PriceOracle) {
	cfg := &config.Config{

























































































































































}	}		t.Error("expected error for withdrawal breaching max LTV")	if err == nil {	err := engine.ValidateWithdrawal(pos.ID, decimal.RequireFromString("1.5"))	// LTV = $30,000 / $21,250 = 1.41 > 0.50 → rejected	// Try to withdraw 1.5 BTC → remaining 0.5 BTC × $42,500 = $21,250	store.CreateLoan(loan)	}		Status:               domain.LoanActive,		AccruedInterestUSD:   decimal.Zero,		OutstandingUSD:       decimal.RequireFromString("30000"),		CollateralPositionID: pos.ID,		UserID:               pos.UserID,	loan := &domain.Loan{	store.CreatePosition(pos)	}		Status: domain.PositionActive,		Amount: decimal.RequireFromString("2.0"),		Asset:  "BTC",	pos := &domain.CollateralPosition{	engine, store, _ := setupTestEngine("42500")func TestValidateWithdrawal_WouldBreachLTV(t *testing.T) {}	}		t.Error("expected error for loan exceeding max LTV")	if err == nil {	err := engine.ValidateLoanRequest(pos.ID, decimal.RequireFromString("30000"))	// Try to borrow $30,000 against $42,500 collateral → LTV = 0.706 > 0.50	store.CreatePosition(pos)	}		Status: domain.PositionActive,		Amount: decimal.RequireFromString("1.0"),		Asset:  "BTC",	pos := &domain.CollateralPosition{	engine, store, _ := setupTestEngine("42500")func TestValidateLoanRequest_ExceedsMaxLTV(t *testing.T) {}	}		t.Errorf("expected LIQUIDATING, got %s (LTV=%s)", result.Status, result.CurrentLTV)	if result.Status != domain.LTVStatusLiquidating {	}		t.Fatalf("unexpected error: %v", err)	if err != nil {	result, err := engine.CalculateLTV(loan.ID)	oracle.SetPrice("BTC", decimal.RequireFromString("25000"), "TEST")	// Crash BTC to $25,000 → LTV = 20000/25000 = 0.80 → LIQUIDATING	store.CreateLoan(loan)	}		Status:               domain.LoanActive,		AccruedInterestUSD:   decimal.Zero,		OutstandingUSD:       decimal.RequireFromString("20000"),		CollateralPositionID: pos.ID,	loan := &domain.Loan{	store.CreatePosition(pos)	}		Status: domain.PositionActive,		Amount: decimal.RequireFromString("1.0"),		Asset:  "BTC",	pos := &domain.CollateralPosition{	engine, store, oracle := setupTestEngine("42500")func TestLTV_LiquidationThreshold(t *testing.T) {}	}		t.Errorf("expected WARNING, got %s (LTV=%s)", result.Status, result.CurrentLTV)	if result.Status != domain.LTVStatusWarning {	}		t.Fatalf("unexpected error: %v", err)	if err != nil {	result, err := engine.CalculateLTV(loan.ID)	store.CreateLoan(loan)	}		Status:               domain.LoanActive,		AccruedInterestUSD:   decimal.Zero,		OutstandingUSD:       decimal.RequireFromString("20000"),		CollateralPositionID: pos.ID,	loan := &domain.Loan{	// Loan $20,000 → LTV = 20000/42500 = 0.4706 → WARNING	store.CreatePosition(pos)	}		Status: domain.PositionActive,		Amount: decimal.RequireFromString("1.0"),		Asset:  "BTC",	pos := &domain.CollateralPosition{	engine, store, _ := setupTestEngine("42500")func TestLTV_WarningThreshold(t *testing.T) {}	}		t.Errorf("expected LTV %s, got %s", expectedLTV, result.CurrentLTV)	if !result.CurrentLTV.Equal(expectedLTV) {	expectedLTV := decimal.RequireFromString("0.352941")	}		t.Errorf("expected SAFE, got %s (LTV=%s)", result.Status, result.CurrentLTV)	if result.Status != domain.LTVStatusSafe {	}		t.Fatalf("unexpected error: %v", err)	if err != nil {	result, err := engine.CalculateLTV(loan.ID)	store.CreateLoan(loan)	}		Status:               domain.LoanActive,		AccruedInterestUSD:   decimal.Zero,		OutstandingUSD:       decimal.RequireFromString("15000"),		CollateralPositionID: pos.ID,	loan := &domain.Loan{	// Loan $15,000 → LTV = 15000/42500 = 0.3529 → SAFE	store.CreatePosition(pos)	}		Status: domain.PositionActive,		Amount: decimal.RequireFromString("1.0"),		Asset:  "BTC",	pos := &domain.CollateralPosition{	// Deposit 1 BTC at $42,500 → collateral value = $42,500	engine, store, _ := setupTestEngine("42500")func TestLTV_SafePosition(t *testing.T) {}	return engine, store, priceOracle	engine := risk.NewEngine(cfg, store, priceOracle)	priceOracle := oracle.NewPriceOracle(cfg)	store := repository.NewInMemoryStore()	}		OraclePollIntervalSec: 9999, // disable auto-poll		DefaultBTCPriceUSD:   decimal.RequireFromString(btcPrice),		CriticalThreshold:    decimal.RequireFromString("0.60"),		WarningThreshold:     decimal.RequireFromString("0.40"),		LiquidationPenalty:   decimal.RequireFromString("0.10"),		LiquidationThreshold: decimal.RequireFromString("0.70"),		MaxLTV:               decimal.RequireFromString("0.50"),