package risk
package risk

import (
	"log"














































































































































































































}	return e.Messagefunc (e *RiskError) Error() string {}	Message stringtype RiskError struct {// ─── Errors ──────────────────────────────────────────────────────────────────}	return atRisk	}		}			atRisk = append(atRisk, *result)		if result.Status == domain.LTVStatusLiquidating || result.Status == domain.LTVStatusCritical {		}			continue			log.Printf("[Risk] Error calculating LTV for loan %s: %v", loan.ID, err)		if err != nil {		result, err := e.CalculateLTV(loan.ID)	for _, loan := range loans {	var atRisk []domain.LTVResult	}		return nil		log.Printf("[Risk] Error fetching active loans: %v", err)	if err != nil {	loans, err := e.store.GetAllActiveLoans()func (e *Engine) ScanAllPositions() []domain.LTVResult {// ScanAllPositions evaluates all active loans and returns those needing liquidation.}	return nil	}		}			Message: "withdrawal would breach max LTV: " + newLTV.Round(4).String(),		return &RiskError{	if newLTV.GreaterThan(e.cfg.MaxLTV) {	newLTV := existingDebt.Div(newCollateralValue)	}		return &RiskError{Message: "withdrawal would leave zero collateral with outstanding debt"}	if newCollateralValue.IsZero() {	newCollateralValue := remainingCollateral.Mul(priceFeed.PriceUSD)	}		return nil // No loans, withdrawal is safe	if existingDebt.IsZero() {	existingDebt := e.store.TotalOutstandingForPosition(positionID)	}		return &RiskError{Message: "cannot withdraw more than deposited"}	if remainingCollateral.IsNegative() {	remainingCollateral := position.Amount.Sub(withdrawAmount)	}		return &RiskError{Message: "no price for asset: " + position.Asset}	if !ok {	priceFeed, ok := e.oracle.GetPrice(position.Asset)	}		return err	if err != nil {	position, err := e.store.GetPosition(positionID)func (e *Engine) ValidateWithdrawal(positionID uuid.UUID, withdrawAmount decimal.Decimal) error {// ValidateWithdrawal checks if withdrawing collateral would breach max LTV.}	return nil	}		}				" > " + e.cfg.MaxLTV.String(),			Message: "loan would exceed max LTV: " + newLTV.Round(4).String() +		return &RiskError{	if newLTV.GreaterThan(e.cfg.MaxLTV) {	newLTV := newTotalDebt.Div(collateralValue)	}		return &RiskError{Message: "collateral has zero value"}	if collateralValue.IsZero() {	newTotalDebt := existingDebt.Add(requestedAmountUSD)	existingDebt := e.store.TotalOutstandingForPosition(positionID)	collateralValue := position.Amount.Mul(priceFeed.PriceUSD)	}		return &RiskError{Message: "no price available for asset: " + position.Asset}	if !ok {	priceFeed, ok := e.oracle.GetPrice(position.Asset)	}		return &RiskError{Message: "position is not active"}	if position.Status != domain.PositionActive {	}		return err	if err != nil {	position, err := e.store.GetPosition(positionID)func (e *Engine) ValidateLoanRequest(positionID uuid.UUID, requestedAmountUSD decimal.Decimal) error {// ValidateLoanRequest checks if a new loan would exceed the max LTV.}	}		return domain.LTVStatusSafe	default:		return domain.LTVStatusWarning	case ltv.GreaterThanOrEqual(e.cfg.WarningThreshold):		return domain.LTVStatusCritical	case ltv.GreaterThanOrEqual(e.cfg.CriticalThreshold):		return domain.LTVStatusLiquidating	case ltv.GreaterThanOrEqual(e.cfg.LiquidationThreshold):	switch {func (e *Engine) classifyLTV(ltv decimal.Decimal) domain.LTVStatus {// classifyLTV determines the risk status based on current LTV.}	}, nil		PriceUpdatedAt:       priceFeed.Timestamp,		Status:               status,		LiquidationThreshold: e.cfg.LiquidationThreshold,		MaxLTV:               e.cfg.MaxLTV,		CurrentLTV:           ltv.Round(6),		LoanOutstandingUSD:   totalDebt,		CollateralValueUSD:   collateralValue,		CollateralAmount:     position.Amount,		CollateralAsset:      position.Asset,		LoanID:               loan.ID,	return &domain.LTVResult{	status := e.classifyLTV(ltv)	ltv := totalDebt.Div(collateralValue)	// LTV = total debt / collateral value	}		}, nil			PriceUpdatedAt:       priceFeed.Timestamp,			Status:               domain.LTVStatusLiquidating,			LiquidationThreshold: e.cfg.LiquidationThreshold,			MaxLTV:               e.cfg.MaxLTV,			CurrentLTV:           decimal.NewFromInt(999), // infinite LTV			LoanOutstandingUSD:   totalDebt,			CollateralValueUSD:   collateralValue,			CollateralAmount:     position.Amount,			CollateralAsset:      position.Asset,			LoanID:               loan.ID,		return &domain.LTVResult{	if collateralValue.IsZero() {	// Guard against division by zero	collateralValue := position.Amount.Mul(priceFeed.PriceUSD)	// Denominator: collateral value = amount × current price	totalDebt := loan.OutstandingUSD.Add(loan.AccruedInterestUSD)	// Numerator: total debt = outstanding principal + accrued interest	}		return nil, &RiskError{Message: "no price available for asset: " + position.Asset}	if !ok {	priceFeed, ok := e.oracle.GetPrice(position.Asset)	}		return nil, err	if err != nil {	position, err := e.store.GetPosition(loan.CollateralPositionID)	}		return nil, err	if err != nil {	loan, err := e.store.GetLoan(loanID)func (e *Engine) CalculateLTV(loanID uuid.UUID) (*domain.LTVResult, error) {//   LIQUIDATING: LTV >= LiquidationThreshold  (>= 70%)//   CRITICAL:    CriticalThreshold <= LTV < LiquidationThreshold  (60-70%)//   WARNING:     WarningThreshold <= LTV < CriticalThreshold  (40-60%)//   SAFE:        LTV < WarningThreshold  (default 40%)// Classification:////   LTV = (Loan Outstanding + Accrued Interest) / (Collateral Amount × Current Price)// Formula://// CalculateLTV computes the current LTV ratio for a loan.}	return &Engine{cfg: cfg, store: store, oracle: oracle}func NewEngine(cfg *config.Config, store *repository.InMemoryStore, oracle *oracle.PriceOracle) *Engine {// NewEngine creates a new risk engine.}	oracle *oracle.PriceOracle	store  *repository.InMemoryStore	cfg    *config.Configtype Engine struct {// Engine performs LTV calculations and risk classification.)	"github.com/shopspring/decimal"	"github.com/google/uuid"	"github.com/cryptolend/protocol-defi/internal/repository"	"github.com/cryptolend/protocol-defi/internal/oracle"	"github.com/cryptolend/protocol-defi/internal/domain"	"github.com/cryptolend/protocol-defi/internal/config"